export const emptyCandidate = {
  id: 0,
  name: "",
  surname: "",
  CVAddress: "",
  phoneNumbers: [],
  emailAdresses: [],
  address: "",
  extraAddress: "",
  zipCode: "",
  city: "",
  country: "",
  mapsCoord: { lat: 51.509865, lng: -0.118092 },
  jobs: [],
  mobility: [],
  skills: [],
  comment: "",
  salaryExpectation: 0,
  departments: [],
  keywords: [],
  diplomas: [],
  placedJob: undefined,
  situation: false,
};
