export const emptyCandidate = {
  id: 0,
  name: "",
  surname: "",
  CVAddress: "",
  phoneNumbers: [],
  emailAdresses: [],
  address: "",
  extraAddress: "",
  zipCode: "",
  city: "",
  country: "",
  mapsCoord: "",
  creatorMember: {},
  previousJobs: [],
  requestedJob: { id: 0, name: "" },
  skills: [],
  comment: "",
  salaryExpectation: 0,
  departments: [],
  keywords: [],
  situation: "free",
};
