# Generated by Django 4.0.2 on 2022-02-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assignedcandidate_and_more'),
        ('comments', '0002_alter_comment_owner_alter_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='tasks.task'),
        ),
    ]
