# Generated by Django 4.0.2 on 2022-02-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_members', '0002_hrmember_user'),
        ('tasks', '0002_alter_task_assignedcandidate_and_more'),
        ('comments', '0003_alter_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='hr_members.hrmember'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'),
        ),
    ]
