# Generated by Django 4.0.2 on 2022-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_settings_emailtemplates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pageTitle',
            field=models.TextField(default=['datetime', 'timezone']),
            preserve_default=False,
        ),
    ]
