# Generated by Django 4.0.2 on 2022-04-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_settings_pagetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('template', models.TextField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.settings')),
            ],
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='settings',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='SMSTemplate',
        ),
    ]
