# Generated by Django 4.0.2 on 2022-04-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_messagetemplate_remove_smstemplate_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
