# Generated by Django 4.0.2 on 2022-04-16 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_messagetemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageTemplate', to='settings.settings'),
        ),
    ]
