# Generated by Django 4.0.2 on 2022-02-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_members', '0002_hrmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
