# Generated by Django 4.0.2 on 2022-02-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_members', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('CVAddress', models.CharField(max_length=255)),
                ('phoneNumbers', models.JSONField()),
                ('emailAdresses', models.JSONField()),
                ('address', models.TextField()),
                ('extraAddress', models.TextField()),
                ('zipCode', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('mapsCoord', models.JSONField()),
                ('previousJobs', models.JSONField()),
                ('skills', models.JSONField()),
                ('comment', models.TextField()),
                ('salaryExpectation', models.IntegerField()),
                ('departments', models.JSONField()),
                ('keywords', models.JSONField()),
                ('diplomas', models.JSONField()),
                ('situation', models.BooleanField(default=False)),
                ('creatorMember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_members.hrmember')),
                ('placedJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
        ),
    ]
