# Generated by Django 4.0.2 on 2022-02-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('hr_members', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='creatorMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatorMember', to='hr_members.hrmember'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='placedJob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placedJob', to='jobs.job'),
        ),
    ]
