# Generated by Django 4.0.2 on 2022-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_creatormember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='departments',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='diplomas',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='emailAdresses',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='keywords',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mapsCoord',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phoneNumbers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previousJobs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(null=True),
        ),
    ]
