# Generated by Django 4.0.2 on 2022-04-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_rename_situation_candidate_isplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='isPlaced',
            new_name='situation',
        ),
    ]
