# Generated by Django 4.0.2 on 2022-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_rename_isplaced_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mobility',
            field=models.JSONField(null=True),
        ),
    ]
