# Generated by Django 4.0.2 on 2022-04-05 12:41

import api.v1.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_mobility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CVAddress',
            field=models.FileField(upload_to=api.v1.candidates.models.cvUploadTo),
        ),
    ]
