# Generated by Django 4.0.2 on 2022-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_candidate_cvaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CVAddress',
            field=models.TextField(null=True),
        ),
    ]
