# Generated by Django 4.0.2 on 2022-04-09 21:42

import api.v1.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidate_cvaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='CVAddress',
        ),
        migrations.AddField(
            model_name='candidate',
            name='CVFile',
            field=models.FileField(null=True, upload_to=api.v1.candidates.models.cvUploadTo),
        ),
    ]
