# Generated by Django 4.0.2 on 2022-04-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_remove_candidate_cvaddress_candidate_cvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='extraAddress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salaryExpectation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zipCode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
