# Generated by Django 4.0.2 on 2022-04-10 00:20

import api.v1.candidates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company'),
        ('hr_members', '0003_alter_hrmember_user'),
        ('candidates', '0011_alter_candidate_address_alter_candidate_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CVFile',
            field=models.FileField(blank=True, null=True, upload_to=api.v1.candidates.models.cvUploadTo),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='creatorMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatorMember', to='hr_members.hrmember'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='diplomas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='emailAdresses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='extraAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mapsCoord',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobility',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phoneNumbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='placedJob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placedJob', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salaryExpectation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zipCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
