# Generated by Django 4.0.2 on 2022-04-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_alter_candidate_cvfile_alter_candidate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
