# Generated by Django 4.0.2 on 2022-02-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('hr_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('situation', models.CharField(max_length=255)),
                ('createdDate', models.DateField(auto_now_add=True, null=True)),
                ('endDate', models.DateField(null=True)),
                ('assignedCandidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate')),
                ('assignedMember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_members.hrmember')),
            ],
        ),
    ]
