# Generated by Django 4.0.2 on 2022-02-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_members', '0001_initial'),
        ('candidates', '0002_alter_candidate_creatormember_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedCandidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedCandidate', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignedMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedMember', to='hr_members.hrmember'),
        ),
    ]
