# Generated by Django 4.0.2 on 2022-04-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_mobility'),
        ('tasks', '0002_alter_task_assignedcandidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedCandidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='candidates.candidate'),
        ),
    ]
