# Generated by Django 4.0.2 on 2022-04-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_assignedcandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isAppropriate',
            field=models.BooleanField(default=False),
        ),
    ]
