import { ICandidate } from "../interfaces/Candidate";

const candidates: ICandidate[] = [
  {
    id: 1,
    name: "Example",
    surname: "Candidate 1",
    city: "Ankara",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 2,
    name: "Example",
    surname: "Candidate",
    city: "Paris",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 3,
    name: "Example",
    surname: "Candidate",
    city: "London",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 4,
    name: "Example",
    surname: "Candidate",
    city: "New York",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 5,
    name: "Example",
    surname: "Candidate",
    city: "Berlin",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 6,
    name: "Example",
    surname: "Candidate",
    city: "Ankara",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 7,
    name: "Example",
    surname: "Candidate",
    city: "Paris",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 8,
    name: "Example",
    surname: "Candidate",
    city: "London",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 9,
    name: "Example",
    surname: "Candidate",
    city: "New York",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
  {
    id: 10,
    name: "Example",
    surname: "Candidate",
    city: "Berlin",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: { lat: 39.62076, lng: 32.55389 },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
  },
];

export default candidates;
