import { ICandidate } from "../interfaces/Candidate";

const candidates: ICandidate[] = [
  {
    id: 1,
    name: "Example",
    surname: "Candidate 1",
    city: "Ankara",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 39.925533,
      lng: 32.866287,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 2,
    name: "Example",
    surname: "Candidate",
    city: "Paris",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 48.864716,
      lng: 2.349014,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 3,
    name: "Example",
    surname: "Candidate",
    city: "London",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 51.509865,
      lng: -0.118092,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 4,
    name: "Example",
    surname: "Candidate",
    city: "New York",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 40.73061,
      lng: -73.935242,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 5,
    name: "Example",
    surname: "Candidate",
    city: "Berlin",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 52.520008,
      lng: 13.404954,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 6,
    name: "Example",
    surname: "Candidate",
    city: "Ankara",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 39.925533,
      lng: 32.866287,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 7,
    name: "Example",
    surname: "Candidate",
    city: "Paris",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 48.864716,
      lng: 2.349014,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 8,
    name: "Example",
    surname: "Candidate",
    city: "London",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 51.509865,
      lng: -0.118092,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 9,
    name: "Example",
    surname: "Candidate",
    city: "New York",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 40.73061,
      lng: -73.935242,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],
    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
  {
    id: 10,
    name: "Example",
    surname: "Candidate",
    city: "Berlin",
    CVAddress: "Example",
    phoneNumbers: ["Example", "Example"],
    emailAdresses: ["Example", "Example"],
    address: "Example",
    extraAddress: "Example",
    zipCode: "Example",
    country: "Example",
    mapsCoord: {
      lat: 52.520008,
      lng: 13.404954,
    },
    creatorMember: { id: 1, name: "Example", surname: "Member" },
    previousJobs: ["Example", "Example"],

    skills: [
      { id: 1, name: "Example", level: "Prof." },
      { id: 2, name: "Example", level: "Prof." },
    ],
    comment: "Example",
    salaryExpectation: 5000,
    departments: ["Example", "Example"],
    keywords: ["Example", "Example"],
    diplomas: ["Example", "Example"],
    situation: false,
  },
];

export default candidates;
