import { ITask } from "../interfaces/Task";

const tasks: ITask[] = [
  {
    id: 1,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 2,
    name: "Example Task",
    description: "Example Task Description",
    situation: "completed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 3,
    name: "Example Task",
    description: "Example Task Description",
    situation: "closed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 4,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 5,
    name: "Example Task",
    description: "Example Task Description",
    situation: "completed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 6,
    name: "Example Task",
    description: "Example Task Description",
    situation: "open",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 7,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 8,
    name: "Example Task",
    description: "Example Task Description",
    situation: "completed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 9,
    name: "Example Task",
    description: "Example Task Description",
    situation: "open",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 10,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 11,
    name: "Example Task",
    description: "Example Task Description",
    situation: "completed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 12,
    name: "Example Task",
    description: "Example Task Description",
    situation: "closed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 13,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 14,
    name: "Example Task",
    description: "Example Task Description",
    situation: "closed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 15,
    name: "Example Task",
    description: "Example Task Description",
    situation: "closed",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 16,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 17,
    name: "Example Task",
    description: "Example Task Description",
    situation: "open",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 18,
    name: "Example Task",
    description: "Example Task Description",
    situation: "open",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
  {
    id: 19,
    name: "Example Task",
    description: "Example Task Description",
    situation: "on-progress",
    assignedCandidate: {
      id: 1,
      name: "Example",
      surname: "Candidate 1",
      city: "Ankara",
      CVAddress: "Example",
      phoneNumbers: ["Example", "Example"],
      emailAdresses: ["Example", "Example"],
      address: "Example",
      extraAddress: "Example",
      zipCode: "Example",
      country: "Example",
      mapsCoord: { lat: 39.62076, lng: 32.55389 },
      creatorMember: { id: 1, name: "Example", surname: "Member" },
      previousJobs: ["Example", "Example"],
      skills: [
        { id: 1, name: "Example", level: "Prof." },
        { id: 2, name: "Example", level: "Prof." },
      ],
      comment: "Example",
      salaryExpectation: 5000,
      departments: ["Example", "Example"],
      keywords: ["Example", "Example"],
      diplomas: ["Example", "Example"],
    },
    assignedMember: {
      id: 1,
      name: "Member",
      surname: "1",
    },
  },
];

export default tasks;
